### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by emmannaemeka** [reubwn/collinearity#1]
I am trying to use cillinearity. I have my transcript fasta generated using MARKER and a reference fasta.

However running 

/opt/anaconda3/bin/diamond blastp -e 1e-5 -p 8 -q /Users/emmannadi/Desktop/collinearity/C_albicans_SC5314_A22_current_orf_coding.fasta -d /Users/emmannadi/Desktop/collinearity/C_albicans_SC5314_A22_current_orf_coding.fasta  -a csc.aa.vs.self 

Gave this error

Opening the database... Database file is not a DIAMOND database, treating as FASTA.
Database file: //Users/emmannadi/Desktop/collinearity/C_albicans_SC5314_A22_current_orf_coding.fasta 
Opening the database file...  [0.000732s]
Loading sequences...  [0.206033s]
Masking sequences...  [1.2115s]
Writing sequences...  [0.055365s]
Hashing sequences...  [0.008439s]
Loading sequences...  [2.1e-05s]
Writing trailer...  [0.001043s]
Closing the input file...  [3.2e-05s]
Closing the database file...  [4.8e-05s]
Database hash = fa0267ee0abc81714410d74d4ba95f7e
Processed 12421 sequences, 18084895 letters.
Total time = 1.48347s
 [1.4846s]
#Target sequences to report alignments for: 25
Opening the input file...  [0.000188s]
Opening the output file...  [0.000186s]
Loading query sequences...  [0.154723s]
Masking queries...  [1.2551s]
Building query seed set...  [0.020259s]
Algorithm: Double-indexed
Building query histograms...  [0.059066s]
Allocating buffers...  [6.9e-05s]
Loading reference sequences...  [0.060164s]
Masking reference...  [1.15703s]
Initializing temporary storage...  [0.003555s]
Building reference histograms...  [0.060739s]
Allocating buffers...  [7.2e-05s]
Processing query block 0, reference block 0, shape 0, index chunk 0.
Building reference seed array...  [0.046846s]
Building query seed array...  [0.044296s]
Computing hash join...  [0.000679s]
Building seed filter...  [0.000687s]
Searching alignments... Illegal instruction: 4

What could be the problem please?

**Comment by reubwn** [comment]
Hi, this looks like a Diamond error - are you sure you correctly formatted the database before running `diamond blastp`? 

E.g.

```
diamond makedb --in C_albicans_SC5314_A22_current_orf_coding.fasta --db C_albicans_SC5314_A22_current_orf_coding.fasta.dmnd
```

**Comment by emmannaemeka** [comment]
Thanks Reubwn,

I figured it out.

However I am not able to follow your instructions

I have two protein fasta files and two gff3 files. I used maker to generate
the fasta and gff3 for one of the genome and downloaded the protein fasta
and gff3 of the reference strain.

While i have generated this

   1.

   >> diamond makedb --in augustus.aa -d augustus.aa
   >> diamond blastp -e 1e-5 -p 8 -q augustus.aa -d augustus.aa -a
augustus.aa.vs.self
   >> diamond view -a augustus.aa.vs.self.daa -o Xyz.blast


This steps  is not clear


 >> perl -lane 'print join("\t",$F[0],$F[8],$F[3],$F[4]) if
($F[2]eq"transcript")' augustus.gff > Xyz.gff

I tried it on my gff3 file

Sample of my gff3

Ca22chr1A_C_albicans_SC5314 CGD chromosome 1 3188341 . . .
ID=Ca22chr1A_C_albicans_SC5314;Name=Ca22chr1A_C_albicans_SC5314
Ca22chr1B_C_albicans_SC5314 CGD chromosome 1 3188396 . . .
ID=Ca22chr1B_C_albicans_SC5314;Name=Ca22chr1B_C_albicans_SC5314
Ca22chr2A_C_albicans_SC5314 CGD chromosome 1 2231883 . . .
ID=Ca22chr2A_C_albicans_SC5314;Name=Ca22chr2A_C_albicans_SC5314
Ca22chr2B_C_albicans_SC5314 CGD chromosome 1 2231750 . . .
ID=Ca22chr2B_C_albicans_SC5314;Name=Ca22chr2B_C_albicans_SC5314
Ca22chr3A_C_albicans_SC5314 CGD chromosome 1 1799298 . . .
ID=Ca22chr3A_C_albicans_SC5314;Name=Ca22chr3A_C_albicans_SC5314
Ca22chr3B_C_albicans_SC5314 CGD chromosome 1 1799271 . . .
ID=Ca22chr3B_C_albicans_SC5314;Name=Ca22chr3B_C_albicans_SC5314
Ca22chr4A_C_albicans_SC5314 CGD chromosome 1 1603259 . . .
ID=Ca22chr4A_C_albicans_SC5314;Name=Ca22chr4A_C_albicans_SC5314
Ca22chr4B_C_albicans_SC5314 CGD chromosome 1 1603311 . . .
ID=Ca22chr4B_C_albicans_SC5314;Name=Ca22chr4B_C_albicans_SC5314
Ca22chr5A_C_albicans_SC5314 CGD chromosome 1 1190869 . . .
ID=Ca22chr5A_C_albicans_SC5314;Name=Ca22chr5A_C_albicans_SC5314
Ca22chr5B_C_albicans_SC5314 CGD chromosome 1 1190991 . . .
ID=Ca22chr5B_C_albicans_SC5314;Name=Ca22chr5B_C_albicans_SC5314
Ca22chr6A_C_albicans_SC5314 CGD chromosome 1 1033292 . . .
ID=Ca22chr6A_C_albicans_SC5314;Name=Ca22chr6A_C_albicans_SC5314
Ca22chr6B_C_albicans_SC5314 CGD chromosome 1 1033212 . . .
ID=Ca22chr6B_C_albicans_SC5314;Name=Ca22chr6B_C_albicans_SC5314
Ca22chr7A_C_albicans_SC5314 CGD chromosome 1 949580 . . .
ID=Ca22chr7A_C_albicans_SC5314;Name=Ca22chr7A_C_albicans_SC5314
Ca22chr7B_C_albicans_SC5314 CGD chromosome 1 949611 . . .
ID=Ca22chr7B_C_albicans_SC5314;Name=Ca22chr7B_C_albicans_SC5314
Ca22chrM_C_albicans_SC5314 CGD chromosome 1 40420 . . .
ID=Ca22chrM_C_albicans_SC5314;Name=Ca22chrM_C_albicans_SC5314
Ca22chrRA_C_albicans_SC5314 CGD chromosome 1 2286237 . . .
ID=Ca22chrRA_C_albicans_SC5314;Name=Ca22chrRA_C_albicans_SC5314
Ca22chrRB_C_albicans_SC5314 CGD chromosome 1 2285697 . . .
ID=Ca22chrRB_C_albicans_SC5314;Name=Ca22chrRB_C_albicans_SC5314
Ca22chr1A_C_albicans_SC5314 CGD gene 4059 4397 . + .
ID=C1_00010W_A;Name=C1_00010W_A;Note=%28orf19.6115%29%20Dubious%20open%20reading%20frame;orf_classification=Dubious;Alias=C1_00010W,C1_00010W_B,CaO19.11880,CaO19.13534,CaO19.4402,CaO19.6115,IPF21113.1,IPF27828.1,orf19.13534,orf19.6115
Ca22chr1A_C_albicans_SC5314 CGD mRNA 4059 4397 . + .
ID=C1_00010W_A-T;Parent=C1_00010W_A;Name=C1_00010W_A;Note=%28orf19.6115%29%20Dubious%20open%20reading%20frame;orf_classification=Dubious;Alias=C1_00010W,C1_00010W_B,CaO19.11880,CaO19.13534,CaO19.4402,CaO19.6115,IPF21113.1,IPF27828.1,orf19.13534,orf19.6115
Ca22chr1A_C_albicans_SC5314 CGD exon 4059 4397 . + .
ID=C1_00010W_A-T-E1;Parent=C1_00010W_A-T
Ca22chr1A_C_albicans_SC5314 CGD CDS 4059 4397 . + 0
ID=C1_00010W_A-P;Parent=C1_00010W_A-T;orf_classification=Dubious;parent_feature_type=ORF
Ca22chr1B_C_albicans_SC5314 CGD gene 4059 4397 . + .
ID=C1_00010W_B;Name=C1_00010W_B;Note=%28orf19.6115%29%20Dubious%20open%20reading%20frame;orf_classification=Dubious
Ca22chr1B_C_albicans_SC5314 CGD mRNA 4059 4397 . + .
ID=C1_00010W_B-T;Parent=C1_00010W_B;Name=C1_00010W_B;Note=%28orf19.6115%29%20Dubious%20open%20reading%20frame;orf_classification=Dubious
Ca22chr1B_C_albicans_SC5314 CGD exon 4059 4397 . + .
ID=C1_00010W_B-T-E1;Parent=C1_00010W_B-T
Ca22chr1B_C_albicans_SC5314 CGD CDS 4059 4397 . + 0
ID=C1_00010W_B-P;Parent=C1_00010W_B-T;orf_classification=Dubious;parent_feature_type=ORF
Ca22chr1A_C_albicans_SC5314 CGD gene 4409 4720 . - .



The second GFF3

##gff-version 3
CBS11016_scaffold_81 . contig 1 303 . . .
ID=CBS11016_scaffold_81;Name=CBS11016_scaffold_81
###
CBS11016_scaffold_75 . contig 1 230 . . .
ID=CBS11016_scaffold_75;Name=CBS11016_scaffold_75
###
CBS11016_scaffold_58 . contig 1 242 . . .
ID=CBS11016_scaffold_58;Name=CBS11016_scaffold_58
###
CBS11016_chr6A . contig 1 938172 . . . ID=CBS11016_chr6A;Name=CBS11016_chr6A
CBS11016_chr6A maker gene 8557 9402 . + .
ID=CBS11016_00004593;Name=CBS11016_00004593;Alias=snap_masked-CBS11016_chr6A-processed-gene-0.0;Note=Similar
to ardh: D-arabitol dehydrogenase (Candida sp. NR20-09-21 OX%3D1125628);
CBS11016_chr6A maker mRNA 8557 9402 . + .
ID=CBS11016_00004593-RA;Parent=CBS11016_00004593;Name=CBS11016_00004593-RA;Alias=snap_masked-CBS11016_chr6A-processed-gene-0.0-mRNA-1;_AED=0.14;_QI=0|-1|0|1|-1|1|1|0|281;_eAED=0.14;Note=Similar
to ardh: D-arabitol dehydrogenase (Candida sp. NR20-09-21 OX%3D1125628);
CBS11016_chr6A maker exon 8557 9402 . + .
ID=CBS11016_00004593-RA:1;Parent=CBS11016_00004593-RA;
CBS11016_chr6A maker CDS 8557 9402 . + 0
ID=CBS11016_00004593-RA:cds;Parent=CBS11016_00004593-RA;
CBS11016_chr6A maker gene 12894 14126 . + .
ID=CBS11016_00004595;Name=CBS11016_00004595;Alias=snap_masked-CBS11016_chr6A-processed-gene-0.1;Note=Similar
to RTT106: Histone chaperone RTT106 (Candida albicans (strain SC5314 / ATCC
MYA-2876) OX%3D237561);
CBS11016_chr6A maker mRNA 12894 14126 . + .
ID=CBS11016_00004595-RA;Parent=CBS11016_00004595;Name=CBS11016_00004595-RA;Alias=snap_masked-CBS11016_chr6A-processed-gene-0.1-mRNA-1;_AED=0.42;_QI=0|-1|0|1|-1|1|1|0|410;_eAED=0.42;_merge_warning=1;Note=Similar
to RTT106: Histone chaperone RTT106 (Candida albicans (strain SC5314 / ATCC
MYA-2876) OX%3D237561);
CBS11016_chr6A maker exon 12894 14126 . + .
ID=CBS11016_00004595-RA:1;Parent=CBS11016_00004595-RA;
CBS11016_chr6A maker CDS 12894 14126 . + 0
ID=CBS11016_00004595-RA:cds;Parent=CBS11016_00004595-RA;
CBS11016_chr6A maker gene 14662 15909 . + .
ID=CBS11016_00004597;Name=CBS11016_00004597;Alias=snap_masked-CBS11016_chr6A-processed-gene-0.2;Note=Similar
to orf19.1180: 2-aminoadipate transaminase (Candida albicans (strain SC5314
/ ATCC MYA-2876) OX%3D237561);
CBS11016_chr6A maker mRNA 14662 15909 . + .
ID=CBS11016_00004597-RA;Parent=CBS11016_00004597;Name=CBS11016_00004597-RA;Alias=snap_masked-CBS11016_chr6A-processed-gene-0.2-mRNA-1;_AED=0.41;_QI=0|-1|0|1|-1|1|1|0|415;_eAED=0.41;_merge_warning=1;Note=Similar
to orf19.1180: 2-aminoadipate transaminase (Candida albicans (strain SC5314
/ ATCC MYA-2876) OX%3D237561);
CBS11016_chr6A maker exon 14662 15909 . + .
ID=CBS11016_00004597-RA:1;Parent=CBS11016_00004597-RA;
CBS11016_chr6A maker CDS 14662 15909 . + 0
ID=CBS11016_00004597-RA:cds;Parent=CBS11016_00004597-RA;



How do I format my perl -lane 'print join("\t",$F[0],$F[8],$F[3],$F[4]) if
($F[2]eq"transcript")' augustus.gff > Xyz.gff to suit my gff3 file


Nnadi Nnaemeka Emmanuel,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:
 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications

**Comment by reubwn** [comment]
Hard to see, but try `$F[2]eq"mRNA"`

**Comment by emmannaemeka** [comment]
I could send the complete gff3 to you email if i can get it. Will be glad
to have it


Nnadi Nnaemeka Emmanuel,Ph.D
Department of Microbiology,
Faculty of Natural and Applied Science,
Plateau State University, Bokkos, Plateau State, Nigeria.
+2348068124819
Publications:
 https://www.researchgate.net/profile/Emmanuel_Nnadi/publications
