### ISSUE TITLE
Readme instruction different from actual scripts

### ISSUE THREAD

**Issue by emmannaemeka** [reubwn/collinearity#2]
Hello,
Trying to replicate the readme file but cannot find these scripts

/path/to/MCScanX/MCScanX 
>> /path/to/MCScanX/duplicate_gene_classifier 

Can you help?

**Comment by reubwn** [comment]
MCScanX is another program, the output of which the scripts in this repo are designed to work on.

You'll need to install MCScanX from the following: https://github.com/wyp1125/MCScanX

**Comment by emmannaemeka** [comment]
Thanks one more question

I want to compare two genomes. They have different protein fasta and Gff3 files Using collinearity do I need to generate Xyz.blast Xyz and Xyz.gff for each of the genomes or concatenate them and then generate a concatenated Xyz.gff and Xyz.blast?

**Comment by reubwn** [comment]
Yes, you should concatenate the GFF file.
