### ISSUE TITLE
collinearity.pl

### ISSUE THREAD

**Issue by SAMANDOLL** [reubwn/collinearity#4]
(base) appledeMacBook-Pro-4:MCScanX fatima$ perl add_ka_and_ks_to_collinearity.pl -i ../data/at.collinearity -d ../data/at.cds -o at.collinearity.kaks

Can't open perl script "add_ka_and_ks_to_collinearity.pl": No such file or directory

i am facing this problem. anybody guide me. how i can solve this problem

**Comment by reubwn** [comment]
Looks like you need to specify the full path to the program, or add it to your `$PATH` (e.g. `~/bin/`)

**Comment by SAMANDOLL** [comment]
Thank you so much for your reply.

Now i shifted  MCscanX in bin folder and also add the Path. But still i am getting this error. please   help me . i will be veryyyy thankful.

BEGIN failed--compilation aborted at add_ka_and_ks_to_collinearity.pl line 5.

In my mac have Clustalw2.
please guide me about this error.
________________________________

**Comment by reubwn** [comment]
Line 5 refers to the module Getopt::Long - try `cpanm Getopt::Long` or `conda install -c bioconda perl-getopt-long` (if you use conda) to install it.

**Comment by SAMANDOLL** [comment]
according to your instruction, i have installed with conda and CPAN successfully this module. but still have same error.

line 5 ;

use Bio::Tools::Run::Alignment::Clustalw;


please guide me again.

________________________________
